---
# PostgreSQL PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-postgresql-pvc
  namespace: devops-tool
  labels:
    app: sonarqube-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-subdir-external-sc
  resources:
    requests:
      storage: 10Gi
---
# PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-postgresql
  namespace: devops-tool
  labels:
    app: sonarqube-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube-postgresql
  template:
    metadata:
      labels:
        app: sonarqube-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: "sonarqube"
            - name: POSTGRES_PASSWORD
              value: "sonarqube123"
            - name: POSTGRES_DB
              value: "sonarqube"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - sonarqube
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - sonarqube
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: sonarqube-postgresql-pvc
---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-postgresql
  namespace: devops-tool
  labels:
    app: sonarqube-postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: postgresql
  selector:
    app: sonarqube-postgresql
---
# SonarQube Data PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data-pvc
  namespace: devops-tool
  labels:
    app: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-subdir-external-sc
  resources:
    requests:
      storage: 10Gi
---
# SonarQube Extensions PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-extensions-pvc
  namespace: devops-tool
  labels:
    app: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-subdir-external-sc
  resources:
    requests:
      storage: 2Gi
---
# SonarQube Logs PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-logs-pvc
  namespace: devops-tool
  labels:
    app: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-subdir-external-sc
  resources:
    requests:
      storage: 5Gi
---
# SonarQube Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: devops-tool
  labels:
    app: sonarqube
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-sysctl
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - sh
            - -c
            - |
              sysctl -w vm.max_map_count=524288
              sysctl -w fs.file-max=131072
              ulimit -n 131072
              ulimit -u 8192
        - name: wait-for-db
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              until nc -z sonarqube-postgresql 5432; do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done
              echo "PostgreSQL is ready"
      containers:
        - name: sonarqube
          image: sonarqube:25.12.0.117093-community
          imagePullPolicy: IfNotPresent
          env:
            - name: SONAR_JDBC_URL
              value: "jdbc:postgresql://sonarqube-postgresql:5432/sonarqube"
            - name: SONAR_JDBC_USERNAME
              value: "sonarqube"
            - name: SONAR_JDBC_PASSWORD
              value: "sonarqube123"
            - name: SONAR_WEB_JAVAOPTS
              value: "-Xmx1024m -Xms512m"
            - name: SONAR_CE_JAVAOPTS
              value: "-Xmx1024m -Xms512m"
            - name: SONAR_SEARCH_JAVAOPTS
              value: "-Xmx512m -Xms512m"
            - name: SONAR_WEB_CONTEXT
              value: "/sonarqube"
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
            - name: sonarqube-extensions
              mountPath: /opt/sonarqube/extensions
            - name: sonarqube-logs
              mountPath: /opt/sonarqube/logs
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /sonarqube/api/system/status
              port: http
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /sonarqube/api/system/status
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 6
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-data-pvc
        - name: sonarqube-extensions
          persistentVolumeClaim:
            claimName: sonarqube-extensions-pvc
        - name: sonarqube-logs
          persistentVolumeClaim:
            claimName: sonarqube-logs-pvc
---
# SonarQube Service
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: devops-tool
  labels:
    app: sonarqube
spec:
  type: NodePort
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      nodePort: 30090
      protocol: TCP
  selector:
    app: sonarqube
---
# SonarQube Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarqube-ingress
  namespace: devops-tool
  labels:
    app: sonarqube
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10000m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  ingressClassName: nginx
  rules:
    - host: DOMAIN_PLACEHOLDER
      http:
        paths:
          - path: /sonarqube
            pathType: Prefix
            backend:
              service:
                name: sonarqube
                port:
                  number: 9000

